services:
  easycoloc:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: easycoloc_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html 
    depends_on:
      - easycoloc_db


  easycoloc_db:
    image: postgres:16
    container_name: easycoloc_users_db
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    volumes:
      - easycoloc_db_data:/var/lib/postgresql/data





volumes:
  easycoloc_db_data: