
services:
  easycoloc:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: easycoloc_app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html 
    depends_on:
      - easycoloc_db


  easycoloc_db:
    image: postgres:16
    container_name: easycoloc_users_db
    environment:
      POSTGRES_DB: easycoloc_db_name
      POSTGRES_USER: easycoloc
      POSTGRES_PASSWORD: easycoloc
    ports:
      - "5432:5432"
    volumes:
      - easycoloc_db_data:/var/lib/postgresql/data





volumes:
  easycoloc_db_data: